name: intelliStock CI

on:
  push:
    branches:
      - "develop"
      - "main"
  pull_request:
    branches:
      - "develop"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    #    services:
    #      postgres:
    #        image: postgres:15
    #        env:
    #          POSTGRES_DB: intellistock_db
    #          POSTGRES_USER: postgres
    #          POSTGRES_PASSWORD: password
    #        ports:
    #          - 5432:5432
    #        options: >-
    #          --health-cmd pg_isready
    #          --health-interval 10s
    #          --health-timeout 5s
    #          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          export TEST_JWT=$(openssl rand -base64 32)
          mvn clean verify -Djwt.secret=$TEST_JWT
#        env:
#          TEST_JWT_SECRET: ${{ secrets.JWT_SECRET }}
#          TEST_ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
